export const TYPES= {
//CONTADOR
INCREMENTAR:"INCREMENTAR",
RESETEAR:"RESETEAR",
DECREMENTAR:"DECREMENTAR",

//VISIBLE

MOSTRAR:"MOSTRAR",
OCULTAR:"OCULTAR",

//CARRITO

ADD_TO_CART:"ADD_TO_CART", //AGREGA UN PRODUCTO PERO SI YA EXISTE, LO INCREMENTA
REMOVE_ON_ITEM:"REMOVE_ONE_ITEM", //ELIMINA, PERO SI HAY MAS DE UNO RESTA 1 CANTIDAD
RE,PBE_ALL_ITEMS:"REMOVE_ALL_ITEMS", //ELIMINA EL PRODUCTO  INDEPENDIENTEMNETE DE LA CANTIDAD
CLEAR_CARD:"CLEAR_CART" // BORRA TODO
}